// src/modules/chatbot/pdf.service.ts
import { Injectable, Logger } from '@nestjs/common';
import PdfPrinter from 'pdfmake';
import { TDocumentDefinitions, Content } from 'pdfmake/interfaces';
import * as path from 'path';
import * as fs from 'fs'; // Import fs for file operations
import { UniEntity } from '@UniversitiesModule/entities';

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private printer: PdfPrinter;
  private readonly downloadsDir: string; // Directory to save generated files

  constructor() {
    const fontsDirectory = path.join(process.cwd(), 'src', 'fonts', 'static');
    this.downloadsDir = path.join(process.cwd(), 'downloads'); // Define your downloads directory

    // Create the downloads directory if it doesn't exist
    if (!fs.existsSync(this.downloadsDir)) {
      fs.mkdirSync(this.downloadsDir, { recursive: true });
      this.logger.log(`Created downloads directory at: ${this.downloadsDir}`);
    }

    this.logger.log(`PDF Service initializing with font directory: ${fontsDirectory}`);

    const fonts = {
      Roboto: {
        normal: path.join(fontsDirectory, 'Roboto-Regular.ttf'),
        bold: path.join(fontsDirectory, 'Roboto-Medium.ttf'),
        italics: path.join(fontsDirectory, 'Roboto-Italics.ttf'),
        bolditalics: path.join(fontsDirectory, 'Roboto-MediumItalics.ttf'),
      },
    };
    this.printer = new PdfPrinter(fonts);
  }

  // CHANGE RETURN TYPE FROM Promise<Buffer> TO Promise<string> (filename)
  async generateTopUniversitiesPdf(universities: UniEntity[], country: string, limit: number): Promise<string> {
    this.logger.log(`Generating PDF for top ${limit} universities in ${country}.`);

    const tableBody: (string | number)[][] = [];
    tableBody.push(['Rank', 'University', 'Country', 'Website', 'Students']);

    universities.forEach((uni) => {
      tableBody.push([
        uni.rank ? uni.rank.toString() : 'N/A',
        uni.university || 'N/A',
        uni.country || 'N/A',
        uni.website || 'N/A',
        uni.studentPopulation ? uni.studentPopulation.toLocaleString() : 'N/A',
      ]);
    });

    const docDefinition: TDocumentDefinitions = {
      content: [
        { text: `Top ${universities.length} Universities in ${country}`, style: 'header' },
        { text: 'Generated by UniScout Assistant', style: 'subheader' },
        { text: '\n\n' },
        {
          table: {
            headerRows: 1,
            widths: ['auto', '*', 'auto', 'auto', 'auto'],
            body: tableBody,
          },
          layout: {
            fillColor: function (rowIndex, node, columnIndex) {
              return rowIndex % 2 === 0 ? '#F5F5F5' : null;
            },
          },
        } as Content,
      ],
      styles: {
        header: {
          fontSize: 18,
          bold: true,
          margin: [0, 0, 0, 10],
        },
        subheader: {
          fontSize: 14,
          bold: false,
          margin: [0, 10, 0, 5],
        },
      },
      defaultStyle: {
        columnGap: 20,
      },
    };

    // Generate a unique filename
    const filename = `top_universities_${country.replace(/\s+/g, '_')}_${limit}_${Date.now()}.pdf`;
    const filePath = path.join(this.downloadsDir, filename);

    return new Promise((resolve, reject) => {
      const pdfDoc = this.printer.createPdfKitDocument(docDefinition);

      const writeStream = fs.createWriteStream(filePath);

      pdfDoc.pipe(writeStream); // Pipe the PDF content to a file stream

      writeStream.on('finish', () => {
        this.logger.log(`PDF saved to: ${filePath}`);
        resolve(filename); // Resolve with the filename
      });

      writeStream.on('error', (err) => {
        this.logger.error(`Error writing PDF to file: ${err.message}`);
        reject(err);
      });

      pdfDoc.on('error', (err) => {
        this.logger.error(`Error generating PDF (pdfmake error): ${err.message}`);
        reject(err);
      });

      pdfDoc.end(); // Finalize the PDF
    });
  }
}
