// src/modules/chatbot/pdf.service.ts
import { Injectable, Logger } from '@nestjs/common';
import PdfPrinter from 'pdfmake'; // <--- Change this line
import { TDocumentDefinitions, Content } from 'pdfmake/interfaces'; // <--- Remove TableLayoutFunctions
import * as path from 'path';
import { UniEntity } from '@UniversitiesModule/entities';

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private printer: PdfPrinter;

  constructor() {
    // When running in development with 'nest start dev', process.cwd() is the project root (UniScout-API).
    // Your fonts are located in 'UniScout-API/src/fonts'.
    // So, we need to join 'process.cwd()', 'src', and 'fonts'.
    const fontsDirectory = path.join(process.cwd(), 'src', 'fonts', 'static');

    this.logger.log(`PDF Service initializing with font directory: ${fontsDirectory}`);

    const fonts = {
      Roboto: {
        normal: path.join(fontsDirectory, 'Roboto-Regular.ttf'),
        bold: path.join(fontsDirectory, 'Roboto-Medium.ttf'),
        italics: path.join(fontsDirectory, 'Roboto-Italics.ttf'),
        bolditalics: path.join(fontsDirectory, 'Roboto-MediumItalics.ttf'),
      },
    };
    this.printer = new PdfPrinter(fonts);
  }

  async generateTopUniversitiesPdf(universities: UniEntity[], country: string, limit: number): Promise<Buffer> {
    this.logger.log(`Generating PDF for top ${limit} universities in ${country}.`);

    const tableBody: (string | number)[][] = [];
    tableBody.push(['Rank', 'University', 'Country', 'Website', 'Students']);

    universities.forEach((uni) => {
      tableBody.push([
        uni.rank ? uni.rank.toString() : 'N/A',
        uni.university || 'N/A',
        uni.country || 'N/A',
        uni.website || 'N/A',
        uni.studentPopulation ? uni.studentPopulation.toLocaleString() : 'N/A',
      ]);
    });

    const docDefinition: TDocumentDefinitions = {
      content: [
        { text: `Top ${universities.length} Universities in ${country}`, style: 'header' },
        { text: 'Generated by UniScout Assistant', style: 'subheader' },
        { text: '\n\n' },
        {
          // The 'table' property itself contains the table definition
          table: {
            headerRows: 1,
            widths: ['auto', '*', 'auto', 'auto', 'auto'],
            body: tableBody,
          },
          // The 'layout' property is applied to the content block that contains the table.
          // It needs to be at the same level as the 'table' property, not inside it.
          layout: {
            fillColor: function (rowIndex, node, columnIndex) {
              return rowIndex % 2 === 0 ? '#F5F5F5' : null;
            },
          },
        } as Content, // Explicitly cast to Content to satisfy TypeScript if needed, though usually not required with correct structure.
      ],
      styles: {
        header: {
          fontSize: 18,
          bold: true,
          margin: [0, 0, 0, 10],
        },
        subheader: {
          fontSize: 14,
          bold: false,
          margin: [0, 10, 0, 5],
        },
      },
      defaultStyle: {
        columnGap: 20,
      },
    };

    return new Promise((resolve, reject) => {
      const pdfDoc = this.printer.createPdfKitDocument(docDefinition);
      const chunks: Buffer[] = [];
      pdfDoc.on('data', (chunk) => chunks.push(chunk));
      pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
      pdfDoc.on('error', (err) => {
        this.logger.error(`Error generating PDF: ${err.message}`);
        reject(err);
      });
      pdfDoc.end();
    });
  }
}
