import { BadRequestException, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import * as bcrypt from 'bcrypt';
import { plainToClass } from 'class-transformer';
import * as fs from 'fs';
import { FindOptionsWhere, Not, Repository } from 'typeorm';

import { PageMetaDto, ResponseItem, ResponsePaginate } from '@app/common/dtos';
import { convertPath } from '@app/common/utils';
import { Job, StatusEnum, UserRole } from '@Constant/enums';
import { ConfigService } from '@nestjs/config';
import { CreateUserDto } from '@UsersModule/dto/create-user.dto';
import { GetUsersDto } from '@UsersModule/dto/get-users.dto';
import { UpdateUserDto } from '@UsersModule/dto/update-user.dto';
import { UserEntity } from '@UsersModule/entities/user.entity';
import { ChangePasswordDto } from './dto/change-password.dto';
import { ProfileDto } from './dto/profile.dto';
import { UserDto } from './dto/user.dto';
import { avtPathName, baseImageUrl } from '@Constant/url';
import { MailService } from './mail/mail.service';
import { UserListResponseDto } from './dto/user-list-response.dto';
import { AuditLogService } from '../audit/audit.service';
import { AuditActionType } from '../audit/entities/audit-log.entity';
import { ExportUsersDto } from './dto/export-user.dto';
import { parse } from 'json2csv';
import * as XLSX from 'xlsx';

@Injectable()
export class UsersService {
  constructor(
    private readonly configService: ConfigService,

    @InjectRepository(UserEntity)
    private readonly userRepository: Repository<UserEntity>,
    private readonly mailService: MailService,
    private readonly auditLogService: AuditLogService
  ) {}
  getJobDropdownOptions(): string[] {
    return [Job.MARKETING, Job.BUSINESS_DEVELOPMENT];
  }
  getAllJobRoles(): string[] {
    return Object.values(Job);
  }
  getAllUserStatuses(): string[] {
    return Object.values(StatusEnum);
  }
  private generateRandomPassword(): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    const specialChars = '!@#$%^&*()-_+=[]{}|;:,.<>?';
    const allChars = chars + specialChars;
    let password = '';
    let hasCapital = false;
    let hasSpecial = false;

    while (password.length < 8 || !hasCapital || !hasSpecial) {
      password = '';
      hasCapital = false;
      hasSpecial = false;

      for (let i = 0; i < 8; i++) {
        password += allChars.charAt(Math.floor(Math.random() * allChars.length));
      }

      if (!/[A-Z]/.test(password)) {
        password += chars.substring(0, 26).charAt(Math.floor(Math.random() * 26));
      }

      if (!/[!@#$%^&*()-_+=[]{}|;:,.<>?]/.test(password)) {
        password += specialChars.charAt(Math.floor(Math.random() * specialChars.length));
      }

      hasCapital = /[A-Z]/.test(password);
      hasSpecial = /[!@#$%^&*()-_+=[]{}|;:,.<>?]/.test(password);
      while (password.length < 12 && hasCapital && hasSpecial && password.length >= 8) {
        password += allChars.charAt(Math.floor(Math.random() * allChars.length));
      }
    }

    return password
      .split('')
      .sort(() => 0.5 - Math.random())
      .join('');
  }

  async create(
    avatar: Express.Multer.File,
    params: CreateUserDto,
    actorId: number,
    ipAddress?: string,
    userAgent?: string
  ): Promise<ResponseItem<UserDto>> {
    const emailExisted = await this.userRepository.findOneBy({
      email: params.email,
      deletedAt: null,
    } as FindOptionsWhere<UserEntity>);

    if (emailExisted) throw new BadRequestException('Email đã tồn tại');

    if (params.phone) {
      const existPhone = await this.userRepository.findOneBy({
        phone: params.phone,
        deletedAt: null,
      } as FindOptionsWhere<UserEntity>);
      if (existPhone) throw new BadRequestException('Số điện thoại đã tồn tại');
    }

    if (avatar) {
      params = { ...params, avatar: avtPathName('users', avatar.filename) };
    } else {
      params = { ...params, avatar: null };
    }
    let plainTextPassword = params.password;
    const isPasswordAutoGenerated = !plainTextPassword;
    if (isPasswordAutoGenerated) {
      plainTextPassword = this.generateRandomPassword();
    }

    const userParams = this.userRepository.create({
      ...params,
      password: plainTextPassword,
      status: StatusEnum.PENDING,
      role: UserRole.ADMIN,
    });

    const user = await this.userRepository.save(userParams);
    if (isPasswordAutoGenerated) {
      try {
        await this.mailService.sendUserPassword(user.email, plainTextPassword, user.name);
      } catch (emailError) {
        console.error(`Failed to send welcome email to ${user.email}:`, emailError.message);
      }
    }

    await this.auditLogService.log(
      actorId,
      AuditActionType.USER_CREATED,
      user.id,
      null,
      { ...user, password: '[REDACTED]' },
      ipAddress,
      userAgent
    );

    const resultUserDto = plainToClass(UserDto, user, { excludeExtraneousValues: true });

    return new ResponseItem(resultUserDto, 'Tạo mới dữ liệu thành công');
  }

  async resetPassword(id: number): Promise<ResponseItem<UserDto>> {
    const user = await this.userRepository.findOneBy({ id, deletedAt: null } as FindOptionsWhere<UserEntity>);
    if (!user) {
      throw new BadRequestException('Nhân viên không tồn tại');
    }
    const newPassword = await bcrypt.hash(this.configService.get<string>('RESET_PASSWORD'), 10);
    const hashedPassword = await bcrypt.hash(newPassword, 10);

    await this.userRepository.update(id, {
      password: hashedPassword,
    });
    try {
      await this.mailService.sendUserPassword(user.email, newPassword, user.name);
    } catch (emailError) {
      console.error(`Failed to send reset password email to ${user.email}:`, emailError.message);
    }

    const response = await this.userRepository.findOneBy({ id, deletedAt: null } as FindOptionsWhere<UserEntity>);

    const resultDto = plainToClass(UserDto, response, { excludeExtraneousValues: true });

    return new ResponseItem(resultDto, 'Đặt lại mật khẩu thành công');
  }

  async changePassword(id: number, data: ChangePasswordDto): Promise<ResponseItem<UserDto>> {
    const user = await this.userRepository.findOneBy({ id, deletedAt: null } as FindOptionsWhere<UserEntity>);
    if (!user || !bcrypt.compareSync(data.oldPassword, user.password)) {
      throw new BadRequestException('Mật khẩu cũ không chính xác');
    }

    const password = await bcrypt.hash(data.newPassword, 10);
    await this.userRepository.update(id, { password });

    const updatedUser = await this.userRepository.findOneBy({ id, deletedAt: null } as FindOptionsWhere<UserEntity>);
    const resultDto = plainToClass(UserDto, updatedUser, { excludeExtraneousValues: true });
    return new ResponseItem(resultDto, 'Thay đổi mật khẩu thành công');
  }

  async getUsers(params: GetUsersDto): Promise<ResponsePaginate<UserListResponseDto>> {
    const usersQuery = this.userRepository
      .createQueryBuilder('users')
      .select(['users.id', 'users.name', 'users.email', 'users.role', 'users.job', 'users.status', 'users.createdAt'])
      .andWhere('users.deletedAt IS NULL')
      .andWhere('users.role IN (:...allowedRoles)', { allowedRoles: [UserRole.ADMIN, UserRole.USER] });

    if (params.search) {
      const searchTerm = `%${params.search.toLowerCase()}%`;
      usersQuery.andWhere(
        '(LOWER(users.name) LIKE :searchTerm OR LOWER(users.email) LIKE :searchTerm OR LOWER(users.phone) LIKE :searchTerm)',
        { searchTerm }
      );
    }

    if (params.status) {
      if (Array.isArray(params.status) && params.status.length > 0) {
        usersQuery.andWhere('users.status IN (:...statuses)', { statuses: params.status });
      } else if (typeof params.status === 'string') {
        usersQuery.andWhere('users.status = :status', { status: params.status });
      }
    } else {
      usersQuery.andWhere('users.status IN (:...defaultStatuses)', {
        defaultStatuses: [StatusEnum.ACTIVE, StatusEnum.INACTIVE, StatusEnum.PENDING, StatusEnum.BLOCKED],
      });
    }

    if (params.role && params.role.length > 0) {
      usersQuery.andWhere('users.role IN (:...roles)', { roles: params.role });
    }

    if (params.job && params.job.length > 0) {
      usersQuery.andWhere('users.job IN (:...jobs)', { jobs: params.job });
    }

    if (params.createdAtStart || params.createdAtEnd) {
      const startDate = params.createdAtStart ? new Date(params.createdAtStart) : null;
      const endDate = params.createdAtEnd ? new Date(params.createdAtEnd) : null;

      if (startDate && endDate) {
        endDate.setHours(23, 59, 59, 999);
        usersQuery.andWhere('users.createdAt BETWEEN :startDate AND :endDate', {
          startDate: startDate.toISOString(),
          endDate: endDate.toISOString(),
        });
      } else if (startDate) {
        usersQuery.andWhere('users.createdAt >= :startDate', { startDate: startDate.toISOString() });
      } else if (endDate) {
        endDate.setHours(23, 59, 59, 999);
        usersQuery.andWhere('users.createdAt <= :endDate', { endDate: endDate.toISOString() });
      }
    }

    usersQuery.orderBy(`users.${params.orderBy || 'createdAt'}`, params.order || 'DESC');

    usersQuery.skip(params.skip);
    usersQuery.take(params.take);

    const [result, total] = await usersQuery.getManyAndCount();

    const pageMetaDto = new PageMetaDto({ itemCount: total, pageOptionsDto: params });

    const resultDtos = plainToClass(UserListResponseDto, result, { excludeExtraneousValues: true });

    return new ResponsePaginate(resultDtos, pageMetaDto, 'Thành công');
  }

  async getUser(id: number): Promise<ResponseItem<UserDto>> {
    const user = await this.userRepository.findOne({
      where: {
        id,
        deletedAt: null,
      } as FindOptionsWhere<UserEntity>,
    });
    if (!user) throw new BadRequestException('Nhân viên không tồn tại');

    const userWithAvatarUrl = { ...user, avatar: user.avatar ? baseImageUrl + convertPath(user.avatar) : null };
    const resultDto = plainToClass(UserDto, userWithAvatarUrl, { excludeExtraneousValues: true });

    return new ResponseItem(resultDto, 'Thành công');
  }

  async getProfile(id: number): Promise<ResponseItem<ProfileDto>> {
    const user = await this.userRepository.findOne({
      where: { id, deletedAt: null } as FindOptionsWhere<UserEntity>,
    });
    if (!user) throw new BadRequestException('Thông tin cá nhân không tồn tại');

    const result = plainToClass(
      ProfileDto,
      { ...user, avatar: user.avatar ? baseImageUrl + convertPath(user.avatar) : null },
      { excludeExtraneousValues: true }
    );

    return new ResponseItem(result, 'Thành công');
  }

  async update(
    id: number,
    updateUserDto: UpdateUserDto,
    actorId: number,
    ipAddress?: string,
    userAgent?: string
  ): Promise<ResponseItem<UserDto>> {
    const user = await this.userRepository.findOneBy({ id, deletedAt: null } as FindOptionsWhere<UserEntity>);
    if (!user) {
      throw new BadRequestException('Người dùng không tồn tại');
    }
    const oldValue = { ...user, password: '[REDACTED]' };
    const updatePayload: Partial<UserEntity> = {};
    if (updateUserDto.name !== undefined) {
      updatePayload.name = updateUserDto.name;
    }

    if (updateUserDto.email !== undefined) {
      if (updateUserDto.email !== user.email) {
        const emailExisted = await this.userRepository.findOneBy({
          email: updateUserDto.email,
          id: Not(id),
          deletedAt: null,
        } as FindOptionsWhere<UserEntity>);
        if (emailExisted) {
          throw new BadRequestException('Email đã tồn tại');
        }
      }
      updatePayload.email = updateUserDto.email;
    }

    if (updateUserDto.job !== undefined) {
      updatePayload.job = updateUserDto.job;
    }

    if (updateUserDto.status !== undefined) {
      updatePayload.status = updateUserDto.status;
    }

    await this.userRepository.update(id, updatePayload);

    const result = await this.userRepository.findOneBy({ id, deletedAt: null } as FindOptionsWhere<UserEntity>);
    const newValue = { ...result, password: '[REDACTED]' };
    await this.auditLogService.log(actorId, AuditActionType.USER_UPDATED, id, oldValue, newValue, ipAddress, userAgent);
    const resultDto = plainToClass(UserDto, result, { excludeExtraneousValues: true });

    return new ResponseItem(resultDto, 'Cập nhật dữ liệu thành công');
  }

  async deleteUser(id: number): Promise<ResponseItem<null>> {
    const user = await this.userRepository.findOneBy({ id, deletedAt: null } as FindOptionsWhere<UserEntity>);
    if (!user) throw new BadRequestException('Người dùng không tồn tại');
    if (user.status === StatusEnum.ACTIVE) throw new BadRequestException('Không được xóa nhân viên đang hoạt động');

    await this.userRepository.softDelete(id);

    return new ResponseItem(null, 'Xóa nhân viên thành công');
  }

  async uploadAvatar(identityId: number, file: Express.Multer.File): Promise<ResponseItem<any>> {
    const user = await this.userRepository.findOneBy({ identityId, deletedAt: null } as FindOptionsWhere<UserEntity>);

    if (!user) {
      throw new BadRequestException('Nhân viên không tồn tại');
    }

    await this.userRepository
      .createQueryBuilder()
      .update(UserEntity)
      .set({
        avatar: avtPathName('users', file.filename),
      })
      .where('identityId = :identityId', { identityId })
      .execute();

    if (user.avatar && fs.existsSync(user.avatar)) {
      fs.unlinkSync(user.avatar);
    }

    return new ResponseItem(null, 'Cập nhật thông tin thành công');
  }

  async removeAvatar(identityId: number): Promise<ResponseItem<any>> {
    const user = await this.userRepository.findOneBy({ identityId, deletedAt: null } as FindOptionsWhere<UserEntity>);

    if (!user) {
      throw new BadRequestException('Nhân viên không tồn tại');
    }

    await this.userRepository
      .createQueryBuilder()
      .update(UserEntity)
      .set({
        avatar: null,
      })
      .where('identityId = :identityId', { identityId })
      .execute();

    if (user.avatar && fs.existsSync(user.avatar)) {
      fs.unlinkSync(user.avatar);
    }

    return new ResponseItem(null, 'Xóa ảnh đại diện thành công');
  }

  async exportUsers(dto: ExportUsersDto): Promise<Buffer> {
    const query = this.userRepository
      .createQueryBuilder('user')
      .where('user.deletedAt IS NULL')
      .andWhere('user.role = :role', { role: UserRole.ADMIN });

    if (dto.status) query.andWhere('user.status = :status', { status: dto.status });
    if (dto.role?.length) query.andWhere('user.role IN (:...roles)', { roles: dto.role });
    if (dto.job?.length) query.andWhere('user.job IN (:...jobs)', { jobs: dto.job });
    if (dto.search) {
      const search = `%${dto.search.toLowerCase()}%`;
      query.andWhere(
        `(LOWER(user.name) LIKE :search OR LOWER(user.email) LIKE :search OR LOWER(user.phone) LIKE :search)`,
        { search }
      );
    }
    if (dto.createdAtStart || dto.createdAtEnd) {
      if (dto.createdAtStart && dto.createdAtEnd) {
        query.andWhere('user.createdAt BETWEEN :start AND :end', {
          start: new Date(dto.createdAtStart),
          end: new Date(dto.createdAtEnd + 'T23:59:59'),
        });
      } else if (dto.createdAtStart) {
        query.andWhere('user.createdAt >= :start', { start: new Date(dto.createdAtStart) });
      } else {
        query.andWhere('user.createdAt <= :end', { end: new Date(dto.createdAtEnd + 'T23:59:59') });
      }
    }

    const rawData = await query.getMany();

    const data = rawData.map((user) => ({
      id: user.id,
      name: user.name,
      email: user.email,
      phone: user.phone,
      status: user.status,
      job: user.job,
      role: user.role,
      createdAt: user.createdAt,
      address: user.address,
      dateOfBirth: user.dateOfBirth,
      identityId: user.identityId,
    }));

    const selectedFields = dto.fields?.length ? dto.fields : Object.keys(data[0] || {});

    const filteredData = data.map((row) => {
      const filtered = {};
      for (const field of selectedFields) {
        filtered[field] = row[field];
      }
      return filtered;
    });

    if (dto.format === 'xlsx') {
      const ws = XLSX.utils.json_to_sheet(filteredData);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Accounts');
      return XLSX.write(wb, { bookType: 'xlsx', type: 'buffer' });
    } else {
      const csv = parse(filteredData);
      return Buffer.from(csv, 'utf-8');
    }
  }
}
