export const DATE_TIME = {
  YEAR_MONTH_DATE: 'YYYY-MM-DD',
  DAY_MONTH_YEAR: 'DD/MM/YYYY',
  DAY_MONTH_YEAR_TIME: 'DD/MM/YYYY HH:mm:ss',
  YEAR: 'YYYY',
  FULL_YEAR_MONTH_DATE_TIME: 'YYYY-MM-DD HH:mm:ss.SSS',
  TIME_HH_MM_SS: 'HH:mm:ss',
  TIME_HH_MM: 'HH:mm',
};
